### ISSUE TITLE
Can't load video url : Youtube, Vimeo or Dailymotion.

### ISSUE THREAD

**Issue by umanpax** [dev-labs-bg/fullscreen-video-view#20]
I ve tried to load a vimeo url, i tried with many others url, it does not works ! Only your url mp4 example works ...

**Comment by slavipetrov** [comment]
The library's purpose is to load video files directly from file (from the device's internal or external memory) or from an URL which is pointing to a file. For example, in the sample application, there is an mp4 URL, which is working because it points to the video file itself as you've noticed.

If you want to use URLs from Youtube, Vimeo or Dailymotion you can use one of their SDKs (
[YouTube Android Player API](https://developers.google.com/youtube/android/player/), [Vimeo SDK](https://developer.vimeo.com/api/libraries), [Dailymotion Android SDK](https://developer.dailymotion.com/tools/sdks#sdk-android)).
